Repository zhongbai2333/Tomato-Novel-Downloader, pull requests merged in 2025-06, with the labels that each got.

#65 Fix config annotations and text writing
  novel_src/book_parser/book_manager.py
Labels: codex

#85 [Update] 優化 Epub 生成
  novel_src/book_parser/book_manager.py
  novel_src/book_parser/epub_generator.py
Labels: update

#87 [BUG] 修复书籍简介中的错误换行处理
  novel_src/book_parser/book_manager.py
Labels: bug
